export const POSTER_MAKE_REQUEST_BEGIN = 'POSTER_MAKE_REQUEST_BEGIN';
export const POSTER_MAKE_REQUEST_SUCCESS = 'POSTER_MAKE_REQUEST_SUCCESS';
export const POSTER_MAKE_REQUEST_FAILURE = 'POSTER_MAKE_REQUEST_FAILURE';
export const POSTER_MAKE_REQUEST_DISMISS_ERROR = 'POSTER_MAKE_REQUEST_DISMISS_ERROR';
